POST http://localhost:8880/user/save
Content-Type: application/json

{
  "loginName": "222",
  "name": "woca",
  "password": "eqweq12"
}
###
GET http://localhost:8880/category/all/
Accept: application/json

###
GET http://localhost:8880/doc/vote/1
Accept: application/json

###
GET http://localhost:8880/ebook/list?page=1&size=1

###
GET http://127.0.0.1:8880/user/delete/1232242342


###
GET http://localhost:8880/ebook/list?categoryId2=401

###